# Generated by Django 4.1.1 on 2022-09-29 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_alter_imagesmodel_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesmodel',
            name='author',
            field=models.ForeignKey(default='Anonymous', on_delete=django.db.models.deletion.CASCADE, related_name='images_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
